import FormNormalization
import Mathlib.LinearAlgebra.QuadraticForm.Basic

namespace APNRedo
section
variable {E : Type*} [AddCommGroup E] [Module F E] [Nontrivial E]

/-- Genuine APN condition: each derivative fiber contains at most two points. -/
def APN (f : E → E) : Prop :=
  ∀a, a≠0 → ∀c x y z,
    f (x+a)+f x=c → f (y+a)+f y=c → f (z+a)+f z=c →
    x=y ∨ x=z ∨ y=z

def derivative (f : E → E) (a x : E) : E := f (x+a)+f x

theorem binary_neg_eq (x : E) : -x=x := by
  apply neg_eq_iff_add_eq_zero.mpr
  exact binary_add_self x

theorem binary_add_cancel (x a : E) : (x+a)+a=x := by
  rw [add_assoc,binary_add_self,add_zero]

theorem derivative_pair (f : E → E) (a x : E) :
    derivative f a (x+a)=derivative f a x := by
  simp only [derivative,binary_add_cancel]
  exact add_comm _ _

theorem add_ne_self (x a : E) (ha : a≠0) : x+a≠x := by
  intro h
  exact ha (add_left_cancel (h.trans (add_zero x).symm))

theorem apn_derivative_fiber (f : E → E) (hf : APN f)
    (a x y : E) (ha : a≠0) :
    derivative f a y=derivative f a x ↔ y=x ∨ y=x+a := by
  constructor
  · intro h
    have hp := hf a ha (derivative f a x) x (x+a) y rfl
      (derivative_pair f a x) h
    rcases hp with hp | hp | hp
    · exact False.elim (add_ne_self x a ha hp.symm)
    · exact Or.inl hp.symm
    · exact Or.inr hp.symm
  · rintro (rfl | rfl)
    · rfl
    · exact derivative_pair f a x

/-- Constant output offsets leave every derivative unchanged. -/
theorem derivative_add_constant (f : E → E) (c a x : E) :
    derivative (fun y => f y+c) a x=derivative f a x := by
  unfold derivative
  calc
    (f (x+a)+c)+(f x+c) = (f (x+a)+f x)+(c+c) := by abel
    _ = _ := by rw [binary_add_self,add_zero]

theorem apn_add_constant_iff (f : E → E) (c : E) :
    APN (fun x => f x+c) ↔ APN f := by
  have hd := derivative_add_constant f c
  dsimp only [derivative] at hd
  unfold APN
  simp only [hd]

/-- The actual mathlib quadratic polar is the normalized derivative. -/
theorem quadratic_polar_eq_derivative (Q : QuadraticMap F E E) (a x : E) :
    Q.polarBilin a x=derivative Q a x+Q a := by
  rw [QuadraticMap.polarBilin_apply_apply]
  simp only [QuadraticMap.polar,sub_eq_add_neg,binary_neg_eq,derivative]
  rw [add_comm a x]
  abel

theorem quadratic_polar_diagonal (Q : QuadraticMap F E E) (a : E) :
    Q.polarBilin a a=0 := by
  rw [QuadraticMap.polarBilin_apply_apply,QuadraticMap.polar_self]
  simpa only [two_smul] using binary_add_self (Q a)

/-- APN plus genuine quadraticity gives the actual two-element linear kernel. -/
theorem apn_quadratic_polar_kernel (Q : QuadraticMap F E E) (hQ : APN Q)
    (a x : E) (ha : a≠0) :
    Q.polarBilin a x=0 ↔ x=0 ∨ x=a := by
  have hqa : derivative Q a 0=Q a := by simp [derivative]
  rw [quadratic_polar_eq_derivative]
  have hz : derivative Q a x+Q a=0 ↔ derivative Q a x=Q a := by
    rw [add_eq_zero_iff_eq_neg,binary_neg_eq]
  rw [hz,←hqa,apn_derivative_fiber Q hQ a 0 x ha,zero_add]

/-- The kernel is exactly the line generated by the direction. -/
theorem apn_quadratic_kernel_span (Q : QuadraticMap F E E) (hQ : APN Q)
    (a : E) (ha : a≠0) :
    LinearMap.ker (Q.polarBilin a)=Submodule.span F {a} := by
  apply le_antisymm
  · intro x hx
    have hh := (apn_quadratic_polar_kernel Q hQ a x ha).mp hx
    rcases hh with rfl | rfl
    · exact Submodule.zero_mem _
    · exact Submodule.subset_span (by simp)
  · apply Submodule.span_le.mpr
    intro x hx
    have hx' : x=a := by simpa using hx
    subst x
    exact quadratic_polar_diagonal Q a

variable [FiniteDimensional F E]

theorem apn_quadratic_kernel_finrank (Q : QuadraticMap F E E) (hQ : APN Q)
    (a : E) (ha : a≠0) :
    Module.finrank F (LinearMap.ker (Q.polarBilin a))=1 := by
  rw [apn_quadratic_kernel_span Q hQ a ha]
  exact finrank_span_singleton ha

theorem apn_quadratic_direction_rank (Q : QuadraticMap F E E) (hQ : APN Q)
    (a : E) (ha : a≠0) :
    Module.finrank F (LinearMap.range (Q.polarBilin a))+1=Module.finrank F E := by
  have h := (Q.polarBilin a).finrank_range_add_finrank_ker
  rwa [apn_quadratic_kernel_finrank Q hQ a ha] at h

#print axioms apn_quadratic_direction_rank
end
end APNRedo
