import QuadraticThreeRadicalLine
import QuadraticFourAffine
import ThreeCoordinateExtension

namespace BooleanANF.QuadraticFour

def radicalVector (q : V → F₂) : TripleBlock :=
  ![polar q ![0,1,0,0] ![0,0,1,0],
    polar q ![1,0,0,0] ![0,0,1,0],
    polar q ![1,0,0,0] ![0,1,0,0]]

theorem radicalVector_poly (a b c d e f g h i j k : F₂) :
    radicalVector (poly a b c d e f g h i j k) = ![i,g,f] := by
  simp [radicalVector, polar_poly]

theorem lastBasis_radical_poly (a b c d e f g h i j k : F₂) :
    IsRadical (poly a b c d e f g h i j k) lastBasis ↔ h=0 ∧ j=0 ∧ k=0 := by
  simp [isRadical_poly, QuadraticFourRaw.inRadical, lastBasis]

/-- The last-coordinate radical condition reduces a general quadratic to its
three-dimensional alternating matrix, with the vector read from actual polars. -/
theorem radicalVector_shape {q : V → F₂} (hq : HasDegreeLE q 2)
    (hlast : IsRadical q lastBasis) (hn : radicalVector q ≠ 0) (x : V) :
    IsRadical q x ↔ dropLast x = 0 ∨ dropLast x = radicalVector q := by
  revert hlast hn
  apply quadratic_induction hq
  intro a b c d e f g h i j k hlast hn
  rw [lastBasis_radical_poly] at hlast
  obtain ⟨rfl,rfl,rfl⟩ := hlast
  have hnonzero : f ≠ 0 ∨ g ≠ 0 ∨ i ≠ 0 := by
    apply Classical.byContradiction
    intro hz
    simp only [not_or, not_not] at hz
    exact hn (by rw [radicalVector_poly, hz.1, hz.2.1, hz.2.2]; funext j; fin_cases j <;> rfl)
  rw [radical_three_coordinates a b c d e f g i hnonzero x, radicalVector_poly]
  simp [funext_iff, Fin.forall_fin_succ, dropLast]

theorem radicalVector_zero_all {q : V → F₂} (hq : HasDegreeLE q 2)
    (hlast : IsRadical q lastBasis) (hz : radicalVector q = 0) :
    ∀ x, IsRadical q x := by
  revert hlast hz
  apply quadratic_induction hq
  intro a b c d e f g h i j k hlast hz x
  rw [lastBasis_radical_poly] at hlast
  obtain ⟨rfl,rfl,rfl⟩ := hlast
  rw [radicalVector_poly] at hz
  have hi : i=0 := congrFun hz 0
  have hg : g=0 := congrFun hz 1
  have hf : f=0 := congrFun hz 2
  simp [isRadical_poly, QuadraticFourRaw.inRadical, hi,hg,hf]

/-- A cost-two row with the common last radical direction is exactly the lift
of the line generated by its nonzero, linearly read radical vector. -/
theorem cost_two_last_radical_shape {q : V → F₂} (hq : HasDegreeLE q 2)
    (hc : cost q = 2) (hlast : IsRadical q lastBasis) :
    radicalVector q ≠ 0 ∧ ∀ x,
      q x = if dropLast x = 0 ∨ dropLast x = radicalVector q then 1 else 0 := by
  have heq := cost_two_eq_radical hq hc
  have hn : radicalVector q ≠ 0 := by
    intro hz
    have hall := radicalVector_zero_all hq hlast hz
    have hqone : q = fun _ => 1 := by
      rw [heq]
      funext x
      simp [radicalIndicator, hall x]
    rw [hqone, cost_const_one] at hc
    norm_num at hc
  refine ⟨hn,?_⟩
  intro x
  conv_lhs => rw [heq]
  simp only [radicalIndicator, radicalVector_shape hq hlast hn x]

end BooleanANF.QuadraticFour
